// integrations/figma.ts
// Figma REST API client.
// Creates files, writes frame specs, generates shareable URLs.
// The Design Agent calls this to publish wireframe specs for human review.

import { integrations } from "../config/integrations";

const { figma: cfg } = integrations;

async function figmaFetch<T>(
  endpoint: string,
  method: "GET" | "POST" | "PUT" | "DELETE" = "GET",
  body?: unknown
): Promise<T> {
  if (!cfg.accessToken) {
    console.log(`[Figma stub] ${method} ${endpoint}`);
    return {
      key:  "stub-file-key",
      name: "AgentSDLC Design",
      frames: [],
      shareUrl: "https://figma.com/stub",
    } as unknown as T;
  }

  const res = await fetch(`https://api.figma.com/v1${endpoint}`, {
    method,
    headers: {
      "X-Figma-Token": cfg.accessToken,
      "Content-Type":  "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Figma ${method} ${endpoint} → ${res.status}: ${text}`);
  }

  return res.json() as Promise<T>;
}

// ── Create a new Figma file ───────────────────────────────────────────────────

export interface FigmaFileResult {
  key:  string;
  name: string;
}

export async function createFigmaFile(name: string): Promise<FigmaFileResult> {
  // Figma REST API does not support file creation directly via REST in free plans.
  // In production: use Figma Plugin API or a template file + duplicate.
  // Here we return the configured project file for now.
  return {
    key:  cfg.projectId || "stub-file-key",
    name: `AgentSDLC — ${name}`,
  };
}

// ── Write component spec as a comment on a file ───────────────────────────────

export async function addDesignSpec(fileKey: string, spec: {
  title:      string;
  components: string[];
  screens:    string[];
  notes:      string;
}): Promise<string> {
  const message = [
    `## ${spec.title}`,
    "",
    "### Screens",
    ...spec.screens.map(s => `- ${s}`),
    "",
    "### Components",
    ...spec.components.map(c => `- ${c}`),
    "",
    "### Design Notes",
    spec.notes,
    "",
    "_Generated by AgentSDLC Design Agent_",
  ].join("\n");

  await figmaFetch(`/files/${fileKey}/comments`, "POST", { message });
  return `https://www.figma.com/file/${fileKey}`;
}

// ── Get shareable link for a file ────────────────────────────────────────────

export function getFigmaShareUrl(fileKey: string, nodeId?: string): string {
  const base = `https://www.figma.com/file/${fileKey}`;
  return nodeId ? `${base}?node-id=${encodeURIComponent(nodeId)}` : base;
}

// ── List frames in a file (for referencing in gate PRs) ──────────────────────

export async function getFileFrames(fileKey: string): Promise<Array<{ id: string; name: string }>> {
  const file = await figmaFetch<{ document: { children: Array<{ id: string; name: string; type: string }> } }>(
    `/files/${fileKey}`
  );
  return (file.document?.children ?? []).filter(n => n.type === "FRAME");
}
