#!/usr/bin/env node
// scripts/init-project.ts
//
// Exports ensureProjectOverview(hostPath) — called automatically at the start
// of every pipeline run in orchestrator/run.ts. No manual step needed.
//
// Can also be run directly to force a refresh:
//   npm run project:init          (uses cached file if < 7 days old)
//   npm run project:reinit        (force regenerate regardless of age)

import * as path from "path";
import * as fs   from "fs";

const OVERVIEW_PATH = path.resolve(__dirname, "../memory/project-overview.md");
const MAX_AGE_DAYS  = 7;

// ── Staleness check ───────────────────────────────────────────────────────────

function isOverviewFresh(): boolean {
  if (!fs.existsSync(OVERVIEW_PATH)) return false;
  const age = (Date.now() - fs.statSync(OVERVIEW_PATH).mtimeMs) / (1000 * 60 * 60 * 24);
  return age < MAX_AGE_DAYS;
}

// ── Core: generate and write project-overview.md ──────────────────────────────

export async function ensureProjectOverview(
  hostPath: string,
  opts: { force?: boolean; silent?: boolean } = {}
): Promise<void> {
  const { force = false, silent = false } = opts;
  const log = (msg: string) => { if (!silent) console.log(msg); };

  if (!force && isOverviewFresh()) {
    const age = (Date.now() - fs.statSync(OVERVIEW_PATH).mtimeMs) / (1000 * 60 * 60);
    log(`  [project:init] Using cached memory/project-overview.md (${Math.round(age)}h old)`);
    return;
  }

  log(`  [project:init] Scanning project and generating overview...`);

  // Lazy imports so dotenv has already loaded before these modules are required
  const { scanCodebase }           = await import("../tools/codebase-scanner");
  const { withFailover, resolveModel } = await import("../config/llm-client");
  const { AGENT_MODELS }           = await import("../config/agents");

  const codeCtx = await scanCodebase(hostPath);

  const isEmpty =
    codeCtx.techStack[0]?.startsWith("Unknown") &&
    codeCtx.entryPoints.length === 0 &&
    codeCtx.keyFileExcerpts.length === 0;

  const cfg = AGENT_MODELS.pm_brainstorm;

  const systemPrompt = isEmpty
    ? `You are a product strategist helping a team define a new software product.
Generate a project-overview.md that captures the product vision for an AI pipeline to build against.
Structure:
# Project Overview
## Product Name & Purpose
## Target Users
## Core Features (planned)
## Tech Stack (recommended)
## Key Principles
## What NOT to build (anti-scope)
Output the markdown directly — no preamble.`
    : `You are a senior product analyst. Read the codebase context and write project-overview.md.
This file is read by AI agents (PM, PO, Architect, Dev, QA) before every pipeline run.
It must tell them EXACTLY what product this is so they never hallucinate the wrong product.

Structure:
# Project Overview
## Product Name & Purpose (1-2 sentences — what does this product DO for users?)
## Target Users
## Core Domain Entities (list main data models: e.g. References, Requests, Accounts)
## Existing Features (bullet list of what is ALREADY built — agents must NOT rebuild these)
## Tech Stack (specific: framework, DB, auth, deployment)
## Key API Endpoints (most important routes)
## What NOT to build (anti-scope — prevents generating wrong features)

Be specific — name real files, real routes, real data models from the codebase.
Output the markdown directly — no preamble or commentary.`;

  const userMessage = isEmpty
    ? `Empty project at: ${hostPath}\nGenerate a project-overview.md template for a new product.`
    : `Project at: ${hostPath}

Tech stack: ${codeCtx.techStack.join(", ")}
Entry points: ${codeCtx.entryPoints.join(", ")}
API routes (${codeCtx.apiRoutes.length}): ${codeCtx.apiRoutes.join(", ")}
DB schema: ${codeCtx.dbSchema.join(", ")}

Key file contents:
${codeCtx.keyFileExcerpts.map(f => `### ${f.path}\n${f.content}`).join("\n\n")}

File tree:
${codeCtx.fileTree.slice(0, 2000)}

Write project-overview.md so agents know exactly what product this is.`;

  const content = await withFailover(async (client) => {
    const res = await client.messages.create({
      model:      resolveModel(cfg.model),
      max_tokens: 2048,
      system:     systemPrompt,
      messages:   [{ role: "user", content: userMessage }],
    });
    return res.content[0].type === "text" ? res.content[0].text : "";
  }, "init-project");

  if (!content.trim()) {
    log(`  [project:init] ⚠ LLM returned empty — skipping overview write`);
    return;
  }

  fs.mkdirSync(path.dirname(OVERVIEW_PATH), { recursive: true });

  const header = [
    `<!-- Auto-generated by AgentSDLC on ${new Date().toISOString()} -->`,
    `<!-- Edit freely — agents use this as their product context on every run -->`,
    `<!-- Regenerates automatically every ${MAX_AGE_DAYS} days, or: npm run project:reinit -->`,
    "",
  ].join("\n");

  fs.writeFileSync(OVERVIEW_PATH, header + content, "utf8");
  log(`  [project:init] ✓ memory/project-overview.md written`);
  if (!silent) {
    console.log(`  [project:init]   Review and edit it to correct any inaccuracies.`);
  }
}

// ── CLI entry point (npm run project:init) ────────────────────────────────────

async function cli() {
  // dotenv must be loaded before ensureProjectOverview imports llm-client
  const dotenv = await import("dotenv");
  dotenv.config({ path: path.resolve(__dirname, "../.env") });

  const { getHostProjectPath } = await import("../config/llm-client");
  const hostPath = process.env.HOST_PROJECT_PATH
    ? path.resolve(__dirname, "..", process.env.HOST_PROJECT_PATH)
    : getHostProjectPath();

  const force = process.argv.includes("--force");

  console.log("\n AgentSDLC — Project Overview\n");
  console.log(` Host project: ${hostPath}`);

  try {
    await ensureProjectOverview(hostPath, { force, silent: false });
  } catch (err) {
    console.warn(`\n [project:init] Failed: ${(err as Error).message}`);
    console.warn(`   Check credentials in .agentsdlc/.env\n`);
    process.exit(0); // non-fatal
  }
}

// Run CLI only when invoked directly (not when imported as a module)
if (require.main === module) {
  cli();
}
